config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cams, only: [:show]

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
    resources :jwts, only: %i[index create destroy] do
      collection do
        delete :clean_expired_jwts
      end
    end
  end

  namespace :api do
    match "me" => "application#user_info", via: :options
  end

  namespace :admin do
    root to: "home#index"

    resources :users, except: %i[destroy] do
      member do
        patch :lock
        patch :unlock
        patch :resend_confirmation_mail
        patch :resend_invitation_mail
      end
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

  devise_scope :user do
    resource :registrations,
             only: %i[new create],
             path: "users",
             path_names: { new: "sign_up" },
             controller: "users/registrations",
             as: :user_registration

    resource :invitations,
             only: %i[edit update],
             path: "users",
             controller: "users/invitations",
             as: :user_invitations
  end

  get "users", to: redirect("/users/sign_up")

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  root to: "cams#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/accounts/application_controller.rb
# frozen_string_literal: true

module Accounts
  class ApplicationController < ::ApplicationController
    before_action :authenticate_user!
    before_action :set_page_layout_data, if: -> { request.format.html? }

    protected

      def set_page_layout_data
        prepare_meta_tags title: t("accounts.#{controller_name}.#{params[:action]}.title")
        @_sidebar_name = "accounts"
      end
  end
end

app/controllers/accounts/jwts_controller.rb
# frozen_string_literal: true

module Accounts
  class JwtsController < Accounts::ApplicationController
    before_action :set_user

    def index
      @whitelisted_jwts = @user.whitelisted_jwts
    end

    def create
      exp_seconds = params[:exp_hours].to_i.hours
      user_encoder = Warden::JWTAuth::UserEncoder.new
      payload = user_encoder.helper.payload_for_user(current_user, "user")
      payload["exp"] = Time.now.to_i + exp_seconds.to_i
      payload["aud"] = params[:aud]
      jwt = Warden::JWTAuth::TokenEncoder.new.call(payload)
      Rails.logger.debug "jwt: #{jwt}"
      if @user.whitelisted_jwts.create(jti: payload["jti"], aud: payload["aud"], exp: Time.at(payload["exp"]))
        redirect_to account_jwts_path, alert: t(".created", jwt: jwt)
      else
        render :index
      end
    end

    def destroy
      @jwt = @user.whitelisted_jwts.find(params[:id])
      @jwt.destroy!
      redirect_to account_jwts_path, notice: t(".deleted")
    end

    def clean_expired_jwts
      @user.whitelisted_jwts.where("exp < ?", Time.now).each do |jwt|
        jwt.destroy
      end
      redirect_to account_jwts_path, notice: t(".done")
    end

    private

      def set_user
        @user = current_user
      end
  end
end

app/controllers/accounts/passwords_controller.rb
# frozen_string_literal: true

module Accounts
  class PasswordsController < Accounts::ApplicationController
    before_action :set_user

    # GET /account/password
    def show
    end

    # PUT /account/password/
    def update
      if @user.update_with_password(user_params)
        bypass_sign_in @user, scope: :user
        redirect_to after_update_url, notice: t("accounts.passwords.show.updated")
      else
        @user.clean_up_passwords
        render :show
      end
    end

    private

      def set_user
        @user = current_user
      end

      def user_params
        params.require(:user).permit(:password, :password_confirmation, :current_password)
      end

      def after_update_url
        account_password_url
      end
  end
end

app/controllers/accounts/profiles_controller.rb
# frozen_string_literal: true

module Accounts
  class ProfilesController < Accounts::ApplicationController
    before_action :set_user

    # GET /account/profile
    def show
    end

    # PUT /account/profile
    def update
      if @user.update_without_password(user_params)
        redirect_to after_update_url, notice: t("accounts.profiles.show.updated")
      else
        render :show
      end
    end

    private

      def set_user
        @user = current_user
      end

      def user_params
        params.require(:user).permit(:email, :full_name)
      end

      def after_update_url
        account_profile_url
      end
  end
end

app/views/accounts/jwts/index.html.erb
<%- content_for :action_bar do %>
  <ol>
    <li class="action_bar-item">
      <%= link_to t(".actions.clean_expired_jwts"), clean_expired_jwts_account_jwts_path, method: :delete, remote: true %>
    </li>
  </ol>
<% end %>

<div class="row justify-content-center">
  <div class="col-lg-12">
    <h3 class="page-title">
      <%= t(".title") %>
    </h3>
    <%= form_tag account_jwts_path, class: 'form-inline' do -%>
      <div class="form-group">
        <label class="mr-1"><%= t(".form.aud") -%>：</label>
        <%= text_field_tag "aud", nil, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label class="mr-1"><%= t(".form.exp_hours") -%>：</label>
        <%= text_field_tag "exp_hours", nil, class: 'form-control' %>
      </div>
      <div><%= submit_tag t(".actions.create"), class: 'btn btn-primary' %></div>
    <% end -%>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th><%= t(".table.user") %></th>
          <th><%= t(".table.jti") %></th>
          <th><%= t(".table.aud") %></th>
          <th><%= t(".table.exp") %></th>
          <th><%= t(".table.exp_relative") %></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @whitelisted_jwts.each do |jwt| %>
          <tr>
            <td><%= jwt.user.email -%></td>
            <td>
              <% if jwt.exp <= Time.now %>
                <del><%= jwt.jti -%></del>
              <% else %>
                <%= jwt.jti -%>
              <% end %>
            </td>
            <td><%= jwt.aud -%></td>
            <td><%= jwt.exp.in_time_zone -%></td>
            <td>
              <% if jwt.exp <= Time.now %>
                <del><%= time_ago_in_words jwt.exp -%></del>
              <% else %>
                <%= time_ago_in_words jwt.exp -%>
              <% end %>
            </td>
            <td>
              <%= link_to t(".actions.delete"), account_jwt_path(jwt), method: :delete, data: { confirm: '你确定要删除吗？' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>