config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cams, only: [:show]

  namespace :account, module: "accounts" do
    resource :password, only: %i[show update]
    resource :profile, only: %i[show update]
    resources :jwts, only: %i[index create destroy] do
      collection do
        delete :clean_expired_jwts
      end
    end
  end

  namespace :api do
    match "me" => "application#user_info", via: :options
  end

  namespace :admin do
    root to: "home#index"

    resources :users, except: %i[destroy] do
      member do
        patch :lock
        patch :unlock
        patch :resend_confirmation_mail
        patch :resend_invitation_mail
      end
    end
  end

  devise_for :users, skip: %i[registrations invitations], controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

  devise_scope :user do
    resource :registrations,
             only: %i[new create],
             path: "users",
             path_names: { new: "sign_up" },
             controller: "users/registrations",
             as: :user_registration

    resource :invitations,
             only: %i[edit update],
             path: "users",
             controller: "users/invitations",
             as: :user_invitations
  end

  get "users", to: redirect("/users/sign_up")

  get "401", to: "errors#unauthorized", as: :unauthorized
  get "403", to: "errors#forbidden", as: :forbidden
  get "404", to: "errors#not_found", as: :not_found

  root to: "cams#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable, :lockable, :invitable,
         :recoverable, :rememberable, :confirmable, :trackable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  scope :active, -> { where(locked_at: nil) }

  def admin?
    email.in? Settings.admin.emails
  end

  # Failsafe when disabled confirmable
  def confirmed?
    if defined? super
      super
    else
      true
    end
  end

  def pending_reconfirmation?
    if defined? super
      super
    else
      false
    end
  end

  def created_by_invite?
    if defined? super
      super
    else
      false
    end
  end

  include Devise::JWT::RevocationStrategies::Whitelist

  def self.find_for_jwt_authentication(sub)
    find_by(email: sub)
  end

  def jwt_subject
    email
  end

  def expired_jwts
    whitelisted_jwts.where("exp <= ?", Time.now)
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: %i[show edit update lock unlock resend_confirmation_mail resend_invitation_mail]
  # before_action :set_breadcrumbs, only: %i[new edit create update], if: -> { request.format.html? }

  def index
    prepare_meta_tags title: t(".title")

    @users = User.all
    @users = @users.where("email LIKE ?", "%#{params[:user_email]}%") if params[:user_email].present?
    @users = @users.page(params[:page]).per(params[:per_page])
  end

  def show
    prepare_meta_tags title: @user.email
  end

  def new
    prepare_meta_tags title: t(".title")
    @user = User.new
  end

  def edit
    prepare_meta_tags title: t(".title")
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: t(".shared.notice.created")
    else
      prepare_meta_tags title: t("admin.users.new.title")
      render :new
    end
  end

  def update
    if @user.update_without_password(user_params)
      redirect_to admin_user_url(@user), notice: t(".shared.notice.updated")
    else
      prepare_meta_tags title: t("admin.users.edit.title")
      render :edit
    end
  end

  def lock
    unless @user.access_locked?
      @user.lock_access!
    end

    redirect_to admin_user_url(@user), notice: t(".shared.notice.locked")
  end

  def unlock
    if @user.access_locked?
      @user.unlock_access!
    end

    redirect_to admin_user_url(@user), notice: t(".shared.notice.unlocked")
  end

  def resend_confirmation_mail
    if !@user.confirmed? || @user.pending_reconfirmation?
      @user.resend_confirmation_instructions
    end

    redirect_to admin_user_url(@user), notice: t(".shared.notice.sent_confirmation_mail")
  end

  def resend_invitation_mail
    if @user.created_by_invite? && !@user.invited_to_sign_up?
      @user.deliver_invitation
    end

    redirect_to admin_user_url(@user), notice: t(".shared.notice.sent_confirmation_mail")
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_breadcrumbs
      @_breadcrumbs = [{
                         text: t("layouts.sidebar.admin.users"),
                         link: admin_users_path
                       }]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {}).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    layout "sign_in"

    # GET /resource/confirmation/new
    def new
      prepare_meta_tags title: t("users.confirmations.new.title")
      super
    end

    # POST /resource/confirmation
    def create
      prepare_meta_tags title: t("users.confirmations.new.title")
      super
    end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

module Users
  class InvitationsController < Devise::InvitationsController
    layout "sign_in"

    def edit
      prepare_meta_tags title: t("users.invitations.edit.title")
      super
    end

    def update
      raw_invitation_token = update_resource_params[:invitation_token]
      self.resource = accept_resource
      invitation_accepted = resource.errors.empty?

      yield resource if block_given?

      if invitation_accepted
        if Devise.allow_insecure_sign_in_after_accept
          flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
          set_flash_message :notice, flash_message if is_flashing_format?
          sign_in(resource_name, resource)
          respond_with resource, location: after_accept_path_for(resource)
        else
          set_flash_message :notice, :updated_not_active if is_flashing_format?
          respond_with resource, location: new_session_path(resource_name)
        end
      else
        resource.invitation_token = raw_invitation_token
        respond_with_navigational(resource) do
          prepare_meta_tags title: t("users.invitations.edit.title")
          render :edit
        end
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    layout "sign_in"

    # GET /resource/password/new
    def new
      prepare_meta_tags title: t("users.passwords.new.title")
      super
    end

    # POST /resource/password
    def create
      prepare_meta_tags title: t("users.passwords.new.title")
      super
    end

    # GET /resource/password/edit?reset_password_token=abcdef
    def edit
      prepare_meta_tags title: t("users.passwords.edit.title")
      super
    end

    # PUT /resource/password
    def update
      prepare_meta_tags title: t("users.passwords.edit.title")
      super
    end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    layout "sign_in", only: [:new, :create]

    before_action :configure_sign_up_params, only: [:create]

    # GET /resource/sign_up
    def new
      prepare_meta_tags title: t("users.registrations.new.title")
      super
    end

    # POST /resource
    def create
      prepare_meta_tags title: t("users.registrations.new.title")
      super
    end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

      # If you have extra params to permit, append them to the sanitizer.
      def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up) do |user_params|
          user_params.permit(:email, :full_name, :password, :password_confirmation)
        end
      end

      # The path used after sign up.
      def after_sign_up_path_for(resource)
        super(resource)
      end

      # The path used after sign up for inactive accounts.
      def after_inactive_sign_up_path_for(resource)
        new_session_path(resource_name)
      end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    before_action -> { prepare_meta_tags title: t("users.sessions.new.title") },
      if: -> { request.format.html? }, only: [:new, :create]
    protect_from_forgery with: :null_session, if: -> { request.format.json? }
    skip_before_action :verify_signed_out_user, if: -> { request.format.json? }
    respond_to :json, if: -> { request.format.json? }
    layout "sign_in"

    # before_action :configure_sign_in_params, only: [:create]

    def new
      super
    end

    def create
      super
    end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true) do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, id: "user_email", autofocus: true, required: "required", class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :email, class: "invalid-feedback" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, id: "user_password", autocomplete: "off", required: !user.persisted?, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :password, class: "invalid-feedback" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, id: "user_password_confirmation", autocomplete: "off", required: !user.persisted?, class: "form-control", class_for_error: "is-invalid" %>
    <%= f.error_message :password_confirmation, class: "invalid-feedback" %>
  </div>

  <%= f.submit (user.persisted? ? t("shared.form.submit.update") : t("shared.form.submit.create")), class: "btn btn-block btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<%- content_for :action_bar do %>
  <ol>
    <li class="action_bar-item">
      <%= link_to t("shared.actions.back"), admin_user_path(@user), class: "btn text-primary" %>
    </li>
  </ol>
<% end %>

<div class="row justify-content-center">
  <div class="col-lg-12">
    <div class="container">
      <h3 class="page-title">
        <%= t(".title") %>
      </h3>

      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%- content_for :action_bar do %>
  <ol>
    <li class="action_bar-item">
      <%= link_to t(".actions.new"), new_admin_user_path, class: "btn text-primary" %>
    </li>
  </ol>
<% end %>

<div class="row justify-content-center">
  <div class="col-lg-12">
    <div class="container">
      <h3 class="page-title">
        <%= t(".title") %>
      </h3>
      <%= form_tag admin_users_path, method: :get, class: 'form-inline' do -%>
        <div class="form-group">
          <label class="mr-1" for="text-user-name"><%= t(".table.email") -%>：</label>
          <%= text_field_tag 'user_email', params[:user_email], class: 'form-control', id: 'text-user-name' %>
        </div>
        <div><%= submit_tag t(".actions.search"), class: 'btn btn-primary' %></div>
      <% end -%>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th><%= t(".table.id") %></th>
            <th><%= t(".table.email") %></th>
            <th><%= t(".table.created_at") %></th>
            <th><%= t(".table.current_sign_in_at") %></th>
            <th><%= t(".table.status") %></th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= time_tag user.created_at %></td>
              <td><%= time_tag user.current_sign_in_at if user.current_sign_in_at %></td>
              <td>
                <% if user.admin? %>
                    <span class="badge badge-success">
                      <%= t("admin.users.shared.status.admin") %>
                    </span>
                <% end %>
                <% unless user.confirmed? %>
                    <span class="badge badge-warning">
                      <%= t("admin.users.shared.status.pending_confirmation") %>
                    </span>
                <% end %>
                <% if user.pending_reconfirmation? %>
                    <span class="badge badge-warning">
                      <%= t("admin.users.shared.status.pending_reconfirmation") %>
                    </span>
                <% end %>
                <% if user.created_by_invite? && !user.invited_to_sign_up? %>
                    <span class="badge badge-warning">
                      <%= t("admin.users.shared.status.inviting") %>
                    </span>
                <% end %>
                <% if user.access_locked? %>
                    <span class="badge badge-danger">
                      <%= t("admin.users.shared.status.locked") %>
                    </span>
                <% end %>
              </td>
              <td>
                <%= link_to t(".table.actions.show"), admin_user_path(user) %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<%- content_for :action_bar do %>
  <ol>
    <li class="action_bar-item">
      <%= link_to t("shared.actions.back"), admin_users_path, class: "btn text-primary" %>
    </li>
  </ol>
<% end %>

<div class="row justify-content-center">
  <div class="col-lg-12">
    <div class="container">
      <h3 class="page-title">
        <%= t(".title") %>
      </h3>

      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<%- content_for :action_bar do %>
  <ol>
    <li class="action_bar-item">
      <%= link_to t("shared.actions.back"), admin_users_path, class: "btn text-primary" %>
    </li>
    <li class="action_bar-item">
      <%= link_to t("shared.actions.edit"), edit_admin_user_path(@user), class: "btn text-primary" %>
    </li>
    <% if !@user.confirmed? || @user.pending_reconfirmation? %>
      <li class="action_bar-item">
        <%= link_to t(".actions.resend_confirmation_mail"), resend_confirmation_mail_admin_user_path(@user), method: :patch, class: "btn text-primary" %>
      </li>
    <% end %>
    <% if @user.created_by_invite? && !@user.invited_to_sign_up? %>
      <li class="action_bar-item">
        <%= link_to t(".actions.resend_invitation_mail"), resend_invitation_mail_admin_user_path(@user), method: :patch, class: "btn text-primary" %>
      </li>
    <% end %>
    <% unless @user == current_user %>
      <li class="action_bar-item">
        <% if @user.access_locked? %>
          <%= link_to t(".actions.unlock"), unlock_admin_user_path(@user), method: :patch, class: "btn text-danger", data: { confirm: t("admin.users.shared.confirmation.unlock") } %>
        <% else %>
          <%= link_to t(".actions.lock"), lock_admin_user_path(@user), method: :patch, class: "btn text-danger", data: { confirm: t("admin.users.shared.confirmation.lock") } %>
        <% end %>
      </li>
    <% end %>
  </ol>
<% end %>

<div class="row justify-content-center">
  <div class="col-lg-12">
    <div class="container">
      <h3 class="page-title">
        <%= @user.class.model_name.human %> #<%= @user.id %>
      </h3>

      <dl class="row">
        <dt class="col-sm-3">
          <%= t(".email") %>
        </dt>
        <dd class="col-sm-9">
          <%= @user.unconfirmed_email || @user.email %>
          <% if @user.unconfirmed_email %>
            <del><%= @user.email %></del>
          <% end %>
        </dd>

        <dt class="col-sm-3">
          <%= t(".status") %>
        </dt>
        <dd class="col-sm-9">
          <% if @user.admin? %>
              <span class="badge badge-success">
                <%= t("admin.users.shared.status.admin") %>
              </span>
          <% end %>
          <% unless @user.confirmed? %>
              <span class="badge badge-warning">
                <%= t("admin.users.shared.status.pending_confirmation") %>
              </span>
          <% end %>
          <% if @user.pending_reconfirmation? %>
              <span class="badge badge-warning">
                <%= t("admin.users.shared.status.pending_reconfirmation") %>
              </span>
          <% end %>
          <% if @user.created_by_invite? && !@user.invited_to_sign_up? %>
              <span class="badge badge-warning">
                <%= t("admin.users.shared.status.inviting") %>
              </span>
          <% end %>
          <% if @user.access_locked? %>
              <span class="badge badge-danger">
                <%= t("admin.users.shared.status.locked") %>
              </span>
          <% end %>
          &nbsp;
        </dd>

        <dt class="col-sm-3">
          <%= t(".created_at") %>
        </dt>
        <dd class="col-sm-9">
          <%= time_tag @user.created_at %>
        </dd>

        <dt class="col-sm-3">
          <%= t(".current_sign_in_at") %>
        </dt>
        <dd class="col-sm-9">
          <% if @user.current_sign_in_at %>
            <%= time_tag @user.current_sign_in_at %>
          <% end %>
        </dd>
      </dl>
    </div>
  </div>
</div>